name: higlass-scipy19
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - nodejs=10.*
  - pip
  - pip:
    - jupyterlab==0.35.6
    - ipywidgets==7.4.2
    - higlass-python
    - nbserverproxy
